In [1]:
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats

In [2]:
from statsmodels.stats.proportion import proportion_confint
from statsmodels.stats.proportion import proportions_ztest
from statsmodels.stats.weightstats import ztest
from scipy.stats import poisson, norm, t, binom

In [3]:
'# Star Wars & Pokemon App'

st.header('Star Wars & Pokemon Dashboard')

# Reading in data and defining variables
starwars_moc_loose = pd.read_csv('C:/Users/amyby/Desktop/Bootcamp/final_project/data/starwars_moc_loose_v7.csv')
pokemon_final_26 = pd.read_csv('C:/Users/amyby/Desktop/Bootcamp/final_project/data/final_dataset_csv.csv')
pokemon_medians = pd.read_csv('C:/Users/amyby/Desktop/Bootcamp/final_project/pokemons_medians_df.csv')
starwars_medians = pd.read_csv('C:/Users/amyby/Desktop/Bootcamp/final_project/starwars_medians_df.csv')
starwars_year_figure = pd.read_csv('C:/Users/amyby/Desktop/Bootcamp/final_project/starwars_year_figure.csv')
pokemon_year_card = pd.read_csv('C:/Users/amyby/Desktop/Bootcamp/final_project/pokemon_year_card_df.csv')
pokemon_returns = pokemon_year_card['YoY_Growth'].replace([np.inf, -np.inf], np.nan).dropna()
starwars_returns = starwars_year_figure['YoY_Growth'].dropna()
sw_returns_list = starwars_returns.to_list()
poke_returns_list = pokemon_returns.to_list()

2025-10-12 19:16:08.756 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-12 19:16:09.346
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\amyby\miniconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-10-12 19:16:09.347 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-12 19:16:09.347 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [4]:
#H1 - rejecting H0 for both Star Wars & Pokemon Data (Returns are not statistically significantly different from annual inflation rate of 2%)
exp_return = 0.02 # in %

# Perform one-sample t-test for SW data
sw_t_stat, sw_p_value = stats.ttest_1samp(sw_returns_list, exp_return)
# Perform one-sample t-test for Poke data
poke_t_stat, poke_p_value = stats.ttest_1samp(poke_returns_list, exp_return)
# Storing results in pandas df 
test_results_df = pd.DataFrame({
    'Franchise': ['Star Wars', 'Pokemon'],
    'T-Statistic': [sw_t_stat, poke_t_stat],
    'P-Value': [sw_p_value, poke_p_value]})

In [5]:
poke_returns_list

[-0.1745223977741697,
 -0.1622159644752517,
 -0.0239500676124655,
 0.4627059602649006,
 -1.0,
 -0.1287878787878787,
 -0.0689999999999999,
 -0.0659898192686685,
 -0.9704319408638816,
 -0.2272389069264069,
 1.1972077552628124,
 -0.3431997450402358,
 -0.3222235700855219,
 -0.1677927424045818,
 -0.0895209419861282,
 0.3345931262548718,
 -1.0,
 0.0054632729110086,
 -0.1705141493137347,
 0.0123485422188565,
 0.4264408174333416,
 -0.6329072435267126,
 -0.1508928571428571,
 -0.2085804416403786,
 0.0506749574829932,
 0.6106881812893599,
 0.4524613331239695,
 -0.1385999999999999,
 -0.1224719030616406,
 -0.0268803363796283,
 0.6520726321436183,
 -0.7280212081719072,
 -0.7423053020639125,
 -0.2352605191343529,
 0.1649792531120331,
 0.4539820487248895,
 0.9509088236735096,
 -0.0920140632847815,
 0.1007578271932736,
 0.599110530415337,
 0.957010197507974,
 3.886254516258531,
 -0.2613102896400326,
 -0.0701628725358911,
 -0.0650627254719959,
 0.387996878318386,
 -0.9721117153654716,
 0.7498677948175569,
 1.0378513145965549,
 9.850646943239536,
 -0.2477991762179485,
 0.0030183965478083,
 -0.1127009322304468,
 0.4172440456595134,
 -0.7651654701390277,
 -0.4943834009369944,
 -0.208883699064315,
 -0.0700826192803879,
 0.2780606460390427,
 -0.4788225806451612,
 -0.3640021044161792,
 2.2309376672667995,
 0.5994216780373198,
 0.0,
 1.0948493408662898,
 0.4687175522422946,
 0.4572915072685539,
 -0.968498645441754,
 -0.4250666666666667,
 -0.0725881261595546,
 0.0138784696174043,
 0.0588235294117647,
 10.35767528534824,
 -0.2495667422090507,
 -0.1801038535118885,
 0.0779333333333334,
 0.3230873894489454,
 9.038330294956294,
 -0.1791373690337602,
 0.0029668666796194,
 0.1068786914267696,
 0.4619346728853766,
 -0.7680515833173861,
 0.230366709111595,
 -0.1151654515892967,
 0.1228947432166351,
 0.8022484306287039,
 -0.5042072990354247,
 -0.0570826493026336,
 -0.0654615815096727,
 0.0748727984344421,
 0.8208717183119105,
 -0.7497830286402195,
 -0.0156323676323676,
 -0.1794769787852462,
 -0.0934268723469519,
 0.4512393446917191,
 0.0845492012875666,
 -0.1640084323814543,
 -0.1173821077516485,
 0.0364835908424494,
 0.7154670583754965,
 -0.7225041227958899,
 0.4290666666666667,
 0.5124223602484472,
 0.4252540296639671,
 0.8548276395115164,
 -0.2322616777565905,
 2.39894485453756,
 -0.1999190063070325,
 -0.1323486910911167,
 -0.0484047574793382,
 0.2162411476443355]

In [6]:
poke_p_value

np.float64(0.04302090449261267)

In [7]:
#H1 - rejecting H0 for both Star Wars & Pokemon Data (Returns are not statistically significantly different from annual inflation rate of 2%)
exp_return = 0.02 # in %

# Perform one-sample t-test for SW data
sw_t_stat, sw_p_value = stats.ttest_1samp(sw_returns_list, exp_return)
# Perform one-sample t-test for Poke data
poke_t_stat, poke_p_value = stats.ttest_1samp(poke_returns_list, exp_return)
# Storing results in pandas df 
test_results_df = pd.DataFrame({
    'Franchise': ['Star Wars', 'Pokemon'],
    'T-Statistic': [sw_t_stat, poke_t_stat],
    'P-Value': [sw_p_value, poke_p_value]})

#Visualising results - Star Wars
fig, ax1 = plt.subplots(figsize=(10, 6))

# ðŸ”¹ Left Y-axis: Median Selling Price
sns.lineplot(
    data=starwars_medians,
    x='year',
    y='selling_price',
    ax=ax1,
    marker='o',
    color='blue',
    label='Median Selling Price'
)
sns.lineplot(
    data=starwars_medians,
    x='year',
    y='expected_price',
    ax=ax1,
    marker='o',
    color='red',
    label='Expected Price (2% Return)'
)

ax1.set_ylabel('Selling Price', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')

# Create a second Y-axis
ax2 = ax1.twinx()

#Right Y-axis: YoY Growth %
sns.lineplot(
    data=starwars_medians,
    x='year',
    y='YoY_Growth',
    ax=ax2,
    marker='o',
    alpha=0.3,
    color='green',
    label='YoY Growth'
)

ax2.set_ylabel('YoY Growth (%)', color='green')
ax2.tick_params(axis='y', labelcolor='green')

# ðŸ”¸ Titles and Grid
plt.title('Price development for Star Wars Figures')
ax1.grid(True)

# ðŸ”¹ Combine legends from both axes
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines + lines2, labels + labels2, loc='upper left')

plt.tight_layout()
plt.show()

plt.show()

# Visualising Results - Pokemon

fig, ax1 = plt.subplots(figsize=(10, 6))

# ðŸ”¹ Left Y-axis: Median Selling Price
sns.lineplot(
    data=pokemon_medians,
    x='year',
    y='Graded',
    ax=ax1,
    marker='o',
    color='blue',
    label='Median Selling Price'
)
sns.lineplot(
    data=pokemon_medians,
    x='year',
    y='expected_price',
    ax=ax1,
    marker='o',
    color='red',
    label='Expected Price (2% Return)'
)

ax1.set_ylabel('Selling Price', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')

# Create a second Y-axis
ax2 = ax1.twinx()

#Right Y-axis: YoY Growth %
sns.lineplot(
    data=pokemon_medians,
    x='year',
    y='YoY_Growth',
    ax=ax2,
    marker='o',
    alpha=0.3,
    color='green',
    #label='YoY Growth'
)

ax2.set_ylabel('YoY Growth (%)', color='green')
ax2.tick_params(axis='y', labelcolor='green')

# ðŸ”¸ Titles and Grid
plt.title('Graded Price development for Pokemon Cards')
ax1.grid(True)

# ðŸ”¹ Combine legends from both axes
lines, labels = ax1.get_legend_handles_labels()
#lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines + lines2, labels + labels2, loc='upper left')

plt.tight_layout()
plt.show()

plt.show()

C:\Users\amyby\AppData\Local\Temp\ipykernel_42612\4007024242.py:68: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\amyby\AppData\Local\Temp\ipykernel_42612\4007024242.py:70: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\amyby\AppData\Local\Temp\ipykernel_42612\4007024242.py:127: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\amyby\AppData\Local\Temp\ipykernel_42612\4007024242.py:129: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [8]:
# Testing Hypothesis for H2: Market behavior varies by condition and character type. Mint-on-card and iconic figures show higher stability and appreciation.
np.random.seed(42)

n = 100

In [9]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Define the model for growth groups starwars
model = ols(
    'total_growth ~ C(condition) + C(character_type) + C(authenticity_n) '
    '+ C(condition):C(character_type) '
    '+ C(condition):C(authenticity_n) '
    '+ C(authenticity_n):C(character_type) '
    '+ C(condition):C(character_type):C(authenticity_n)',
    data=starwars_moc_loose
).fit()

# Run ANOVA
anova_table_growth_sw = sm.stats.anova_lm(model, typ=2)
anova_table_growth_sw = anova_table_growth_sw.reset_index()

In [ ]:
star

In [18]:
anova_table_growth_sw

,index,sum_sq,df,F,PR(>F)
0,C(condition),5.740032e+07,1.0,42.444564,7.337563e-11
1,C(character_type),1.816948e+09,6.0,223.923137,1.948742e-283
2,C(authenticity_n),2.600570e+06,1.0,1.922987,1.655337e-01
3,C(condition):C(character_type),3.619569e+08,6.0,44.608060,9.637922e-55
4,C(condition):C(authenticity_n),4.515174e+06,1.0,3.338738,6.767223e-02
5,C(authenticity_n):C(character_type),4.566225e+07,6.0,5.627479,7.500548e-06
6,C(condition):C(character_type):C(authenticity_n),1.265909e+07,6.0,1.560124,1.543079e-01
7,Residual,7.036869e+10,52034.0,NaN,NaN

In [10]:
# Define the model for volatility groups starwars
model = ols(
    'volatility_y ~ C(condition) + C(character_type) + C(authenticity_n) '
    '+ C(condition):C(character_type) '
    '+ C(condition):C(authenticity_n) '
    '+ C(authenticity_n):C(character_type) '
    '+ C(condition):C(character_type):C(authenticity_n)',
    data=starwars_moc_loose
).fit()

# Run ANOVA
anova_table_volatility_sw = sm.stats.anova_lm(model, typ=2)
anova_table_volatility_sw = anova_table_volatility_sw.reset_index()

In [11]:
# Visualise H2 for starwars data - growth
sw_groupby_condition = starwars_moc_loose.groupby(['year','condition'])['selling_price'].median().reset_index().sort_values(['condition', 'year'])
sw_groupby_condition['yoy_growth'] = sw_groupby_condition['selling_price'].pct_change()
sw_groupby_condition = sw_groupby_condition.dropna()
sw_groupby_condition

    year  condition  selling_price  yoy_growth
6   2014          0         42.000    0.400000
8   2015          0         46.340    0.103333
10  2016          0         52.275    0.128075
12  2017          0         62.000    0.186035
14  2018          0         60.990   -0.016290
16  2019          0         58.355   -0.043204
18  2020          0         73.130    0.253192
20  2021          0        106.685    0.458840
22  2022          0        108.670    0.018606
24  2023          0        105.815   -0.026272
26  2024          0         99.990   -0.055049
28  2025          0        105.470    0.054805
0   2009          1        172.800    0.638381
1   2010          1        120.960   -0.300000
2   2011          1         82.080   -0.321429
3   2012          1        103.680    0.263158
5   2013          1        174.690    0.684896
7   2014          1        129.100   -0.260977
9   2015          1        182.605    0.414446
11  2016          1        186.950    0.023795
13  2017          1        208.820    0.116983
15  2018          1        209.515    0.003328
17  2019          1        200.240   -0.044269
19  2020          1        240.940    0.203256
21  2021          1        347.500    0.442268
23  2022          1        359.990    0.035942
25  2023          1        317.635   -0.117656
27  2024          1        320.820    0.010027
29  2025          1        335.945    0.047145

In [12]:

fig, ax1 = plt.subplots(figsize=(10, 6))

# ðŸ”¹ Left Y-axis: Median Selling Price by Condition
sns.lineplot(
    data=sw_groupby_condition,
    x='year',
    y='selling_price',
    hue='condition',
    ax=ax1,
    marker='o'
)

ax1.set_ylabel('Selling Price', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')

# Create a second Y-axis
ax2 = ax1.twinx()

# ðŸ”¸ Right Y-axis: YoY Growth by Condition
sns.lineplot(
    data=sw_groupby_condition,
    x='year',
    y='yoy_growth',
    hue='condition',
    ax=ax2,
    marker='o',
    alpha=0.3,
    linestyle='--'
)

ax2.set_ylabel('YoY Growth (%)', color='green')
ax2.tick_params(axis='y', labelcolor='green')

# ðŸ”¸ Title and Grid
plt.title('Price Development and YoY Growth by Condition')
ax1.grid(True)

# ðŸ”¹ Combine Legends from both axes
# Get legend handles and labels from both axes
handles1, labels1 = ax1.get_legend_handles_labels()
handles2, labels2 = ax2.get_legend_handles_labels()

# Remove duplicate labels (optional)
from collections import OrderedDict
combined = OrderedDict(zip(labels1 + labels2, handles1 + handles2))

# Show combined legend
ax1.legend(combined.values(), combined.keys(), loc='upper left')

plt.tight_layout()
st.pyplot(fig)

2025-10-12 19:16:11.397 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-12 19:16:11.666 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-12 19:16:11.667 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-12 19:16:11.668 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [13]:
sw_groupby_condition

    year  condition  selling_price  yoy_growth
6   2014          0         42.000    0.400000
8   2015          0         46.340    0.103333
10  2016          0         52.275    0.128075
12  2017          0         62.000    0.186035
14  2018          0         60.990   -0.016290
16  2019          0         58.355   -0.043204
18  2020          0         73.130    0.253192
20  2021          0        106.685    0.458840
22  2022          0        108.670    0.018606
24  2023          0        105.815   -0.026272
26  2024          0         99.990   -0.055049
28  2025          0        105.470    0.054805
0   2009          1        172.800    0.638381
1   2010          1        120.960   -0.300000
2   2011          1         82.080   -0.321429
3   2012          1        103.680    0.263158
5   2013          1        174.690    0.684896
7   2014          1        129.100   -0.260977
9   2015          1        182.605    0.414446
11  2016          1        186.950    0.023795
13  2017          1        208.820    0.116983
15  2018          1        209.515    0.003328
17  2019          1        200.240   -0.044269
19  2020          1        240.940    0.203256
21  2021          1        347.500    0.442268
23  2022          1        359.990    0.035942
25  2023          1        317.635   -0.117656
27  2024          1        320.820    0.010027
29  2025          1        335.945    0.047145

In [24]:
import os
print("Image exists?", os.path.exists('Users/amyby/Desktop/Bootcamp/final_project/images/pikachu.jpg'))

Image exists? False

In [14]:
pokemon_year_card = pd.merge(
    pokemon_year_card,
    pokemon_final_26[['Card Name', 'Rarity', 'Set Name']],
    on='Card Name',
    how='left'
)

In [15]:
pokemon_year_card.nunique()

Card Name          26
Unnamed: 1        116
Card Name.1        26
year                6
Graded            114
YoY_Growth        113
expected_price    110
Rarity             12
Set Name           15
dtype: int64

In [16]:
pokemon_year_card = pokemon_year_card.rename(columns={'Set Name': 'Set_Name'})

In [20]:
pokemon_year_card.columns= pokemon_year_card.columns.str.lower()

In [22]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import streamlit as st

# Ensure categorical variables are properly formatted as category dtype
pokemon_year_card['graded'] = pokemon_year_card['graded'].astype('category')
pokemon_year_card['rarity'] = pokemon_year_card['rarity'].astype('category')
pokemon_year_card['set_name'] = pokemon_year_card['set_name'].astype('category')

# Define the model using lowercase variables
model = ols(
    'yoy_growth ~ C(graded) + C(rarity) + C(set_name) + C(graded):C(rarity) + C(graded):C(set_name)',
    data=pokemon_year_card
).fit()


# Run ANOVA
anova_table_growth_poke = sm.stats.anova_lm(model, typ=2)

# Display ANOVA table in Streamlit
st.dataframe(anova_table_growth_poke)

c:\Users\amyby\miniconda3\Lib\site-packages\statsmodels\regression\linear_model.py:341: RuntimeWarning: invalid value encountered in dot
  beta = np.dot(self.pinv_wexog, self.wendog)

ValueError: array must not contain infs or NaNs