In [21]:
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats

In [22]:
from statsmodels.stats.proportion import proportion_confint
from statsmodels.stats.proportion import proportions_ztest
from statsmodels.stats.weightstats import ztest
from scipy.stats import poisson, norm, t, binom

In [23]:
'# Star Wars & Pokemon App'

st.header('Star Wars & Pokemon Dashboard')

# Reading in data and defining variables
starwars_moc_loose = pd.read_csv('C:/Users/amyby/Desktop/Bootcamp/final_project/data/starwars_moc_loose_v7.csv')
pokemon_final_26 = pd.read_csv('C:/Users/amyby/Desktop/Bootcamp/final_project/data/final_dataset_csv.csv')
pokemon_medians = pd.read_csv('C:/Users/amyby/Desktop/Bootcamp/final_project/pokemons_medians_df.csv')
starwars_medians = pd.read_csv('C:/Users/amyby/Desktop/Bootcamp/final_project/starwars_medians_df.csv')
starwars_year_figure = pd.read_csv('C:/Users/amyby/Desktop/Bootcamp/final_project/starwars_year_figure.csv')
pokemon_year_card = pd.read_csv('C:/Users/amyby/Desktop/Bootcamp/final_project/pokemon_year_card_df.csv')
pokemon_returns = pokemon_year_card['YoY_Growth'].replace([np.inf, -np.inf], np.nan).dropna()
starwars_returns = starwars_year_figure['YoY_Growth'].dropna()
sw_returns_list = starwars_returns.to_list()
poke_returns_list = pokemon_returns.to_list()

2025-10-13 10:18:24.468 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-13 10:18:24.470 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-13 10:18:24.472 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [24]:
#H1 - rejecting H0 for both Star Wars & Pokemon Data (Returns are not statistically significantly different from annual inflation rate of 2%)
exp_return = 0.02 # in %

# Perform one-sample t-test for SW data
sw_t_stat, sw_p_value = stats.ttest_1samp(sw_returns_list, exp_return)
# Perform one-sample t-test for Poke data
poke_t_stat, poke_p_value = stats.ttest_1samp(poke_returns_list, exp_return)
# Storing results in pandas df 
test_results_df = pd.DataFrame({
    'Franchise': ['Star Wars', 'Pokemon'],
    'T-Statistic': [sw_t_stat, poke_t_stat],
    'P-Value': [sw_p_value, poke_p_value]})

In [25]:
poke_returns_list

[-0.1745223977741697,
 -0.1622159644752517,
 -0.0239500676124655,
 0.4627059602649006,
 -1.0,
 -0.1287878787878787,
 -0.0689999999999999,
 -0.0659898192686685,
 -0.9704319408638816,
 -0.2272389069264069,
 1.1972077552628124,
 -0.3431997450402358,
 -0.3222235700855219,
 -0.1677927424045818,
 -0.0895209419861282,
 0.3345931262548718,
 -1.0,
 0.0054632729110086,
 -0.1705141493137347,
 0.0123485422188565,
 0.4264408174333416,
 -0.6329072435267126,
 -0.1508928571428571,
 -0.2085804416403786,
 0.0506749574829932,
 0.6106881812893599,
 0.4524613331239695,
 -0.1385999999999999,
 -0.1224719030616406,
 -0.0268803363796283,
 0.6520726321436183,
 -0.7280212081719072,
 -0.7423053020639125,
 -0.2352605191343529,
 0.1649792531120331,
 0.4539820487248895,
 0.9509088236735096,
 -0.0920140632847815,
 0.1007578271932736,
 0.599110530415337,
 0.957010197507974,
 3.886254516258531,
 -0.2613102896400326,
 -0.0701628725358911,
 -0.0650627254719959,
 0.387996878318386,
 -0.9721117153654716,
 0.7498677948175569,
 1.0378513145965549,
 9.850646943239536,
 -0.2477991762179485,
 0.0030183965478083,
 -0.1127009322304468,
 0.4172440456595134,
 -0.7651654701390277,
 -0.4943834009369944,
 -0.208883699064315,
 -0.0700826192803879,
 0.2780606460390427,
 -0.4788225806451612,
 -0.3640021044161792,
 2.2309376672667995,
 0.5994216780373198,
 0.0,
 1.0948493408662898,
 0.4687175522422946,
 0.4572915072685539,
 -0.968498645441754,
 -0.4250666666666667,
 -0.0725881261595546,
 0.0138784696174043,
 0.0588235294117647,
 10.35767528534824,
 -0.2495667422090507,
 -0.1801038535118885,
 0.0779333333333334,
 0.3230873894489454,
 9.038330294956294,
 -0.1791373690337602,
 0.0029668666796194,
 0.1068786914267696,
 0.4619346728853766,
 -0.7680515833173861,
 0.230366709111595,
 -0.1151654515892967,
 0.1228947432166351,
 0.8022484306287039,
 -0.5042072990354247,
 -0.0570826493026336,
 -0.0654615815096727,
 0.0748727984344421,
 0.8208717183119105,
 -0.7497830286402195,
 -0.0156323676323676,
 -0.1794769787852462,
 -0.0934268723469519,
 0.4512393446917191,
 0.0845492012875666,
 -0.1640084323814543,
 -0.1173821077516485,
 0.0364835908424494,
 0.7154670583754965,
 -0.7225041227958899,
 0.4290666666666667,
 0.5124223602484472,
 0.4252540296639671,
 0.8548276395115164,
 -0.2322616777565905,
 2.39894485453756,
 -0.1999190063070325,
 -0.1323486910911167,
 -0.0484047574793382,
 0.2162411476443355]

In [26]:
poke_p_value

np.float64(0.04302090449261267)

In [27]:
#H1 - rejecting H0 for both Star Wars & Pokemon Data (Returns are not statistically significantly different from annual inflation rate of 2%)
exp_return = 0.02 # in %

# Perform one-sample t-test for SW data
sw_t_stat, sw_p_value = stats.ttest_1samp(sw_returns_list, exp_return)
# Perform one-sample t-test for Poke data
poke_t_stat, poke_p_value = stats.ttest_1samp(poke_returns_list, exp_return)
# Storing results in pandas df 
test_results_df = pd.DataFrame({
    'Franchise': ['Star Wars', 'Pokemon'],
    'T-Statistic': [sw_t_stat, poke_t_stat],
    'P-Value': [sw_p_value, poke_p_value]})

#Visualising results - Star Wars
fig, ax1 = plt.subplots(figsize=(10, 6))

# ðŸ”¹ Left Y-axis: Median Selling Price
sns.lineplot(
    data=starwars_medians,
    x='year',
    y='selling_price',
    ax=ax1,
    marker='o',
    color='blue',
    label='Median Selling Price'
)
sns.lineplot(
    data=starwars_medians,
    x='year',
    y='expected_price',
    ax=ax1,
    marker='o',
    color='red',
    label='Expected Price (2% Return)'
)

ax1.set_ylabel('Selling Price', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')

# Create a second Y-axis
ax2 = ax1.twinx()

#Right Y-axis: YoY Growth %
sns.lineplot(
    data=starwars_medians,
    x='year',
    y='YoY_Growth',
    ax=ax2,
    marker='o',
    alpha=0.3,
    color='green',
    label='YoY Growth'
)

ax2.set_ylabel('YoY Growth (%)', color='green')
ax2.tick_params(axis='y', labelcolor='green')

# ðŸ”¸ Titles and Grid
plt.title('Price development for Star Wars Figures')
ax1.grid(True)

# ðŸ”¹ Combine legends from both axes
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines + lines2, labels + labels2, loc='upper left')

plt.tight_layout()
plt.show()

plt.show()

# Visualising Results - Pokemon

fig, ax1 = plt.subplots(figsize=(10, 6))

# ðŸ”¹ Left Y-axis: Median Selling Price
sns.lineplot(
    data=pokemon_medians,
    x='year',
    y='Graded',
    ax=ax1,
    marker='o',
    color='blue',
    label='Median Selling Price'
)
sns.lineplot(
    data=pokemon_medians,
    x='year',
    y='expected_price',
    ax=ax1,
    marker='o',
    color='red',
    label='Expected Price (2% Return)'
)

ax1.set_ylabel('Selling Price', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')

# Create a second Y-axis
ax2 = ax1.twinx()

#Right Y-axis: YoY Growth %
sns.lineplot(
    data=pokemon_medians,
    x='year',
    y='YoY_Growth',
    ax=ax2,
    marker='o',
    alpha=0.3,
    color='green',
    #label='YoY Growth'
)

ax2.set_ylabel('YoY Growth (%)', color='green')
ax2.tick_params(axis='y', labelcolor='green')

# ðŸ”¸ Titles and Grid
plt.title('Graded Price development for Pokemon Cards')
ax1.grid(True)

# ðŸ”¹ Combine legends from both axes
lines, labels = ax1.get_legend_handles_labels()
#lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines + lines2, labels + labels2, loc='upper left')

plt.tight_layout()
plt.show()

plt.show()

C:\Users\amyby\AppData\Local\Temp\ipykernel_54000\4007024242.py:68: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\amyby\AppData\Local\Temp\ipykernel_54000\4007024242.py:70: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\amyby\AppData\Local\Temp\ipykernel_54000\4007024242.py:127: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\amyby\AppData\Local\Temp\ipykernel_54000\4007024242.py:129: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [28]:
# Testing Hypothesis for H2: Market behavior varies by condition and character type. Mint-on-card and iconic figures show higher stability and appreciation.
np.random.seed(42)

n = 100

In [29]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Define the model for growth groups starwars
model = ols(
    'total_growth ~ C(condition) + C(character_type) + C(authenticity_n) '
    '+ C(condition):C(character_type) '
    '+ C(condition):C(authenticity_n) '
    '+ C(authenticity_n):C(character_type) '
    '+ C(condition):C(character_type):C(authenticity_n)',
    data=starwars_moc_loose
).fit()

# Run ANOVA
anova_table_growth_sw = sm.stats.anova_lm(model, typ=2)
anova_table_growth_sw = anova_table_growth_sw.reset_index()

In [30]:
anova_table_growth_sw

,index,sum_sq,df,F,PR(>F)
0,C(condition),5.740032e+07,1.0,42.444564,7.337563e-11
1,C(character_type),1.816948e+09,6.0,223.923137,1.948742e-283
2,C(authenticity_n),2.600570e+06,1.0,1.922987,1.655337e-01
3,C(condition):C(character_type),3.619569e+08,6.0,44.608060,9.637922e-55
4,C(condition):C(authenticity_n),4.515174e+06,1.0,3.338738,6.767223e-02
5,C(authenticity_n):C(character_type),4.566225e+07,6.0,5.627479,7.500548e-06
6,C(condition):C(character_type):C(authenticity_n),1.265909e+07,6.0,1.560124,1.543079e-01
7,Residual,7.036869e+10,52034.0,NaN,NaN

In [31]:
anova_table_growth_sw

,index,sum_sq,df,F,PR(>F)
0,C(condition),5.740032e+07,1.0,42.444564,7.337563e-11
1,C(character_type),1.816948e+09,6.0,223.923137,1.948742e-283
2,C(authenticity_n),2.600570e+06,1.0,1.922987,1.655337e-01
3,C(condition):C(character_type),3.619569e+08,6.0,44.608060,9.637922e-55
4,C(condition):C(authenticity_n),4.515174e+06,1.0,3.338738,6.767223e-02
5,C(authenticity_n):C(character_type),4.566225e+07,6.0,5.627479,7.500548e-06
6,C(condition):C(character_type):C(authenticity_n),1.265909e+07,6.0,1.560124,1.543079e-01
7,Residual,7.036869e+10,52034.0,NaN,NaN

In [32]:
# Define the model for volatility groups starwars
model = ols(
    'volatility_y ~ C(condition) + C(character_type) + C(authenticity_n) '
    '+ C(condition):C(character_type) '
    '+ C(condition):C(authenticity_n) '
    '+ C(authenticity_n):C(character_type) '
    '+ C(condition):C(character_type):C(authenticity_n)',
    data=starwars_moc_loose
).fit()

# Run ANOVA
anova_table_volatility_sw = sm.stats.anova_lm(model, typ=2)
anova_table_volatility_sw = anova_table_volatility_sw.reset_index()

In [33]:
# Visualise H2 for starwars data - growth
sw_groupby_condition = starwars_moc_loose.groupby(['year','condition'])['selling_price'].median().reset_index().sort_values(['condition', 'year'])
sw_groupby_condition['yoy_growth'] = sw_groupby_condition['selling_price'].pct_change()
sw_groupby_condition = sw_groupby_condition.dropna()
sw_groupby_condition

    year  condition  selling_price  yoy_growth
6   2014          0         42.000    0.400000
8   2015          0         46.340    0.103333
10  2016          0         52.275    0.128075
12  2017          0         62.000    0.186035
14  2018          0         60.990   -0.016290
16  2019          0         58.355   -0.043204
18  2020          0         73.130    0.253192
20  2021          0        106.685    0.458840
22  2022          0        108.670    0.018606
24  2023          0        105.815   -0.026272
26  2024          0         99.990   -0.055049
28  2025          0        105.470    0.054805
0   2009          1        172.800    0.638381
1   2010          1        120.960   -0.300000
2   2011          1         82.080   -0.321429
3   2012          1        103.680    0.263158
5   2013          1        174.690    0.684896
7   2014          1        129.100   -0.260977
9   2015          1        182.605    0.414446
11  2016          1        186.950    0.023795
13  2017          1        208.820    0.116983
15  2018          1        209.515    0.003328
17  2019          1        200.240   -0.044269
19  2020          1        240.940    0.203256
21  2021          1        347.500    0.442268
23  2022          1        359.990    0.035942
25  2023          1        317.635   -0.117656
27  2024          1        320.820    0.010027
29  2025          1        335.945    0.047145

In [34]:

fig, ax1 = plt.subplots(figsize=(10, 6))

# ðŸ”¹ Left Y-axis: Median Selling Price by Condition
sns.lineplot(
    data=sw_groupby_condition,
    x='year',
    y='selling_price',
    hue='condition',
    ax=ax1,
    marker='o'
)

ax1.set_ylabel('Selling Price', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')

# Create a second Y-axis
ax2 = ax1.twinx()

# ðŸ”¸ Right Y-axis: YoY Growth by Condition
sns.lineplot(
    data=sw_groupby_condition,
    x='year',
    y='yoy_growth',
    hue='condition',
    ax=ax2,
    marker='o',
    alpha=0.3,
    linestyle='--'
)

ax2.set_ylabel('YoY Growth (%)', color='green')
ax2.tick_params(axis='y', labelcolor='green')

# ðŸ”¸ Title and Grid
plt.title('Price Development and YoY Growth by Condition')
ax1.grid(True)

# ðŸ”¹ Combine Legends from both axes
# Get legend handles and labels from both axes
handles1, labels1 = ax1.get_legend_handles_labels()
handles2, labels2 = ax2.get_legend_handles_labels()

# Remove duplicate labels (optional)
from collections import OrderedDict
combined = OrderedDict(zip(labels1 + labels2, handles1 + handles2))

# Show combined legend
ax1.legend(combined.values(), combined.keys(), loc='upper left')

plt.tight_layout()
st.pyplot(fig)

2025-10-13 10:18:26.614 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-13 10:18:26.983 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-13 10:18:26.986 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-13 10:18:26.987 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [35]:
sw_groupby_condition

    year  condition  selling_price  yoy_growth
6   2014          0         42.000    0.400000
8   2015          0         46.340    0.103333
10  2016          0         52.275    0.128075
12  2017          0         62.000    0.186035
14  2018          0         60.990   -0.016290
16  2019          0         58.355   -0.043204
18  2020          0         73.130    0.253192
20  2021          0        106.685    0.458840
22  2022          0        108.670    0.018606
24  2023          0        105.815   -0.026272
26  2024          0         99.990   -0.055049
28  2025          0        105.470    0.054805
0   2009          1        172.800    0.638381
1   2010          1        120.960   -0.300000
2   2011          1         82.080   -0.321429
3   2012          1        103.680    0.263158
5   2013          1        174.690    0.684896
7   2014          1        129.100   -0.260977
9   2015          1        182.605    0.414446
11  2016          1        186.950    0.023795
13  2017          1        208.820    0.116983
15  2018          1        209.515    0.003328
17  2019          1        200.240   -0.044269
19  2020          1        240.940    0.203256
21  2021          1        347.500    0.442268
23  2022          1        359.990    0.035942
25  2023          1        317.635   -0.117656
27  2024          1        320.820    0.010027
29  2025          1        335.945    0.047145

In [36]:
import os
print("Image exists?", os.path.exists('Users/amyby/Desktop/Bootcamp/final_project/images/pikachu.jpg'))

Image exists? False

In [37]:
pokemon_year_card = pd.merge(
    pokemon_year_card,
    pokemon_final_26[['Card Name', 'Rarity', 'Set Name']],
    on='Card Name',
    how='left'
)

In [38]:
pokemon_year_card.nunique()

Card Name          26
Unnamed: 1        116
Card Name.1        26
year                6
Graded            114
YoY_Growth        113
expected_price    110
Rarity             12
Set Name           15
dtype: int64

In [39]:
pokemon_year_card = pokemon_year_card.rename(columns={'Set Name': 'Set_Name'})

In [40]:
pokemon_year_card.columns= pokemon_year_card.columns.str.lower()

In [41]:
sw_groupby_condition

    year  condition  selling_price  yoy_growth
6   2014          0         42.000    0.400000
8   2015          0         46.340    0.103333
10  2016          0         52.275    0.128075
12  2017          0         62.000    0.186035
14  2018          0         60.990   -0.016290
16  2019          0         58.355   -0.043204
18  2020          0         73.130    0.253192
20  2021          0        106.685    0.458840
22  2022          0        108.670    0.018606
24  2023          0        105.815   -0.026272
26  2024          0         99.990   -0.055049
28  2025          0        105.470    0.054805
0   2009          1        172.800    0.638381
1   2010          1        120.960   -0.300000
2   2011          1         82.080   -0.321429
3   2012          1        103.680    0.263158
5   2013          1        174.690    0.684896
7   2014          1        129.100   -0.260977
9   2015          1        182.605    0.414446
11  2016          1        186.950    0.023795
13  2017          1        208.820    0.116983
15  2018          1        209.515    0.003328
17  2019          1        200.240   -0.044269
19  2020          1        240.940    0.203256
21  2021          1        347.500    0.442268
23  2022          1        359.990    0.035942
25  2023          1        317.635   -0.117656
27  2024          1        320.820    0.010027
29  2025          1        335.945    0.047145

In [42]:
sw_returns_list

[-0.775,
 0.1206275720164609,
 -0.8843240761992196,
 5.126488095238096,
 0.3530888187191321,
 0.1151268549545236,
 0.180725477570294,
 -0.1762861297945828,
 0.2939586206896551,
 -0.2212083741951989,
 0.5412537640295647,
 0.2006678270754147,
 -0.0318934911242603,
 0.0197115090764621,
 -0.1651631851829651,
 0.3647329121194715,
 0.0029461279461278,
 -0.5716796055392362,
 0.5914518400587838,
 0.0516737206617932,
 -0.1377455822631984,
 0.073489477257298,
 0.3174308300395256,
 0.140049803486244,
 0.432037685202242,
 0.1828138782710968,
 -0.2456963519980113,
 -0.3165808444902163,
 0.325979505726341,
 -0.9513137557959814,
 2.017273576097105,
 -0.0592604053844963,
 0.1225328947368422,
 0.1573626373626375,
 -0.0758323838460566,
 0.0695890410958905,
 0.2950819672131146,
 0.3988330696202529,
 0.1803464121597737,
 -0.2518567321514134,
 0.0407493395244575,
 -0.097076923076923,
 -0.1167149429204292,
 -0.2536651234567902,
 0.0982165934349963,
 0.0278889150388326,
 0.1423010875787065,
 0.0222489476849068,
 0.1138235294117646,
 -0.1956693952997096,
 0.4580871087765377,
 0.3240768537976584,
 0.2216302006575217,
 -0.040460282108389,
 -0.0632495164410058,
 -0.14908114804873,
 -0.1613685998544042,
 0.5502025462962963,
 0.1204853009799347,
 0.4077128102615357,
 0.1389266907283592,
 0.2123746688139642,
 0.195526417277285,
 -0.099516129032258,
 0.5068362290285986,
 0.3340333359748528,
 -0.1631701400920746,
 0.2237707633334911,
 -0.061602119143835,
 -0.0773494323450024,
 -0.8637754304473079,
 0.8450819672131147,
 -0.1594402487783208,
 0.189260609904339,
 0.4552484223624569,
 0.1070359738594024,
 0.1221207690822321,
 0.1799990166674863,
 0.4936250000000002,
 -0.0894496052668286,
 -0.0587766731514527,
 -0.0638630297506672,
 0.0709318497913769,
 -0.495064935064935,
 -0.9227109053497944,
 2.327371048252912,
 0.4001750218777344,
 0.0948214285714286,
 0.2485728266188223,
 -0.0975179621162637,
 -0.031048708113194,
 -0.0385419778906482,
 0.6305158483530142,
 0.1337907375643225,
 -0.1024541939821818,
 -0.0790804382432812,
 -0.035894046469063,
 -0.271001423825344,
 0.7499999999999998,
 -0.7027943121693121,
 0.7065368567454797,
 0.2466992665036673,
 0.4793750408576847,
 0.3998232434821032,
 -0.1247237830671128,
 -0.0587513975547299,
 0.1060234500728023,
 0.2333275593279058,
 -0.2036516853932584,
 0.2698412698412697,
 -0.094611111111111,
 -0.2432349512180156,
 -0.3694964728776453,
 -0.0747813786008232,
 -0.7429981235666134,
 1.3077339102217418,
 0.2522849777361144,
 0.0805651726396556,
 0.1603740907516453,
 -0.0011940298507462,
 -0.0687387925881649,
 0.2485558408215662,
 0.6024932527952704,
 -0.1197369476301226,
 -0.0546191690962098,
 0.0956970076615428,
 -0.2659747570253747,
 -0.6184770235456234,
 0.4340452261306531,
 0.1233026719229084,
 0.0592708130239811,
 0.1595803423522916,
 0.0495238095238095,
 -0.0502117362371447,
 0.1175955414012739,
 0.3950274275130012,
 -0.0296190378919415,
 0.0483107041364065,
 -0.109136546184739,
 -0.0206243660543219,
 1.9827387802071343,
 -0.6010802469135802,
 0.3926982591876207,
 0.2668310128120552,
 0.0189661788083099,
 0.0261444940556243,
 0.1927129750982961,
 -0.0220210100654916,
 0.325752808988764,
 0.4625228829073156,
 0.0080432993753114,
 -0.0591535693344216,
 0.0387134617264639,
 -0.1414705882352941,
 -0.6211305241521068,
 -0.7921730324074074,
 0.9229028889662376,
 0.1083355959815368,
 -0.070063694267516,
 0.1856340007024937,
 -0.007628499481558,
 -0.200985148145384,
 0.7453764244348964,
 0.2971208391308999,
 -0.1233600132024094,
 -0.0963855421686746,
 -0.0520833333333333,
 0.1686813186813185,
 -0.2366713681241183,
 2.2424242424242427,
 -0.4518273687409772,
 1.4871785986554855,
 -0.6078718216649251,
 1.6851661041037485,
 -0.4721994336676635,
 -0.1729592860008022,
 0.4007093273515414,
 0.2551939058171746,
 0.2155862068965517,
 0.3190740950868036,
 -0.0096774193548386,
 -0.012985884907709,
 0.2430696118982662,
 0.5916637168141592,
 -0.0935960591133004,
 -0.0030179605456864,
 0.0038023281569166,
 -0.1137296965982225,
 -0.9815761264220756,
 12.141891891891891,
 0.7869180234218791,
 0.5587595907928391,
 -0.2148160301899175,
 -0.3633110437780795,
 0.6738871794871795,
 -0.2524693022229847,
 0.3013606557377049,
 0.3085169368756535,
 -0.1831449640911103,
 0.2238067177371834,
 -0.3422573189522342,
 -0.5445973645680819,
 -0.6111111111111112,
 -0.1679894179894179,
 0.4451510333863275,
 0.4850110011001098,
 0.0242615056949717,
 0.1570382424735557,
 0.0471167369901546,
 -0.1231997612118498,
 0.3375744680851065,
 0.3325485954251899,
 0.0466504321252922,
 -0.1422445255474452,
 0.3949047973619828,
 -0.3024173561596828,
 -0.6759585690470333,
 -0.3402209665176688,
 0.0883292854403681,
 0.2216349541930935,
 0.0752812229593309,
 0.1689914163090129,
 0.0100963744837081,
 -0.0515674693321217,
 0.1976047904191615,
 0.3944666666666667,
 0.115265095376966,
 -0.0210048010973936,
 -0.0925650232069357,
 0.0515344528083381,
 -0.2070484581497798,
 0.2042824074074072,
 -0.5436809226333494,
 0.7215669755686605,
 0.2893320283826768,
 0.0967833760318817,
 0.0067479885803269,
 0.2368307983157171,
 -0.0454387549503232,
 0.1933182909964335,
 0.5571210734980179,
 -0.0207215323749462,
 -0.169,
 0.063249097472924,
 0.0129023495857667,
 0.803611334584786,
 0.1275214352976159,
 4.292307692307692,
 0.8687707641196014,
 1.0,
 6.211111111111111,
 -0.889,
 2.783783783783784,
 -0.4,
 5.431269718981584,
 -0.9991945399850716,
 -0.5021246458923513,
 0.8551446183025131,
 0.140958466453674,
 0.5179211469534051,
 -0.2595188902007085,
 -0.0812157448928748,
 0.3073210412147504,
 -0.0586966441282614,
 1.0897232504847525,
 -0.1459299873471109,
 -0.2444444444444444,
 0.1705228758169934,
 -0.0228376793790832,
 0.6786285714285714,
 -0.7693014705882353,
 -0.6901283753873395,
 4.957142857142857,
 0.5514788169464429,
 -0.1685558246174455,
 0.4609450038729665,
 -0.0519172039362063,
 -0.1251342161775231,
 0.2963947839427254,
 0.124176561082403,
 0.4980876521983226,
 -0.4144376258959104,
 0.1085199999999999,
 -0.1655540720961281,
 -0.4022054054054054,
 -0.9357638888888888,
 4.057995495495497,
 0.1432706222865412,
 0.0867575462512171,
 0.0930920168443687,
 0.1639344262295081,
 -0.1264788732394366,
 -0.0154788777813608,
 0.6739272846380608,
 0.1634380197632325,
 -0.0407433881343817,
 -0.0597878495660558,
 -0.1917016317016316,
 -0.6260237628330834,
 0.4910549043800123,
 0.2308647083160941,
 -0.1176470588235294,
 0.4142857142857143,
 -0.0245117845117843,
 -0.0608173408808504,
 0.3744946710768098,
 0.1462032085561497,
 -0.1508817766165905,
 0.17010989010989,
 0.0407588279489106,
 -0.2149431510557661,
 -0.6340229885057471,
 0.3190954773869348,
 -0.001547619047619,
 0.0902587337546201,
 0.1079396325459318,
 0.1383871286151416,
 0.0347697910344229,
 0.2056309703368526,
 0.2432582707812065,
 -0.0429338103756709,
 0.0425233644859812,
 -0.0533953384132676,
 0.098727434152116,
 -0.4414695900447125,
 -0.669945987654321,
 2.941262419637639,
 0.170386297916512,
 0.0231232182451694,
 0.5593808049535605,
 -0.0251747141041931,
 -0.1294093686354378,
 0.4211388200065502,
 0.3663001251069993,
 -0.1146506024096385,
 0.0882368951064176,
 -0.1902260904361744,
 -0.0302056952251528,
 0.7772611464968151,
 -0.0931082679281796,
 0.1404663110057302,
 -0.0345466830679672,
 0.2070883804396592,
 0.1323273619267078,
 0.0305648189480869,
 0.1170917522358396,
 0.3605519758225466,
 0.1127577535624475,
 -0.1167364710136193,
 -0.0917316958765084,
 -0.0243476464567743,
 -0.4585875695340019,
 -0.0722234072810009,
 -0.000881344241565,
 0.1810842426218188,
 0.3455106348433188,
 -0.1094485338481959,
 -0.0160975609756098,
 0.1086321820084836,
 0.7865217391304349,
 -0.2427771790147064,
 -0.0941689623507805,
 0.261341172892696,
 -0.0649226441631505,
 -0.5841405450935564,
 -0.8295304232804233,
 7.48666343355965,
 0.8279950855738734,
 0.0759245365594423,
 0.0252994457801569,
 -0.1923714524561826,
 -0.3805964912280701,
 1.19482524216847,
 1.1093230783128258,
 -0.197595631758462,
 -0.219625633792078,
 -0.1226966292134832,
 -0.4320206699928723,
 -0.905,
 1.344891640866873,
 0.3732065839274712,
 0.5963079289789119,
 -0.1371667202055895,
 0.2018568503350708,
 -0.0126038218040308,
 0.2723333333333333,
 0.4165420949621661,
 -0.0407645945299069,
 0.0264599471481552,
 -0.4274507204101476,
 0.3197730518352697,
 -0.2672398666432707,
 -0.4143318965517241,
 -0.929196906197826,
 5.525986525505294,
 0.6001769780989601,
 -0.0059907834101382,
 0.1836346777932314,
 0.0204065645685636,
 0.0513972055888223,
 0.0854660289876239,
 0.1007668505314136,
 0.2903935468100709,
 -0.1972911536275809,
 0.112094395280236,
 -0.1186472148541114,
 0.4561651668823547,
 -0.5325520833333333,
 -0.6609629924393156,
 2.105633802816901,
 0.5202821869488539,
 0.0993260413214009,
 -0.050854271356784,
 0.2067714951291825,
 -0.0020400552789172,
 0.0781641535147492,
 0.2736799184505607,
 0.2667189550853155,
 -0.2731339322946282,
 -0.0167240360210007,
 -0.4306930693069307,
 -0.9677018633540372,
 6.842307692307692,
 0.1472535556645413,
 -0.0952228278294324,
 0.2376565083864872,
 -0.0186104218362282,
 0.1245745405037441,
 0.0176409546869595,
 0.7852651257647856,
 -0.1337046027892806,
 -0.0392307692307691,
 -0.0639940523847649,
 0.0431966762387729,
 1.024130256530397,
 -0.7422453703703704,
 0.2687471935339021,
 0.4361175013271987,
 -0.0367814675620725,
 0.2161315082512471,
 0.1180771051385893,
 -0.0979866403236429,
 0.3578096479791395,
 0.2974343217084036,
 -0.0465364120781528,
 -0.1130774962742174,
 0.0501995379122033,
 -0.2002,
 -0.3796782528965574,
 -0.3761085729642569,
 0.155395218608658,
 0.1681424177462951,
 0.063831484879917,
 0.0315007875196882,
 -0.092052643059696,
 0.1845118923680626,
 0.4459468595767697,
 0.0533034086127086,
 -0.0045278998535089,
 -0.0452619843924192,
 -0.0728631480616534,
 -0.0320403022670026,
 3.240657853648382,
 0.1567501227295042,
 -0.0797118363536052,
 -0.0388176022319832,
 0.2495322170512881,
 -0.2009483950238058,
 -0.0960452656111098,
 0.2828418408707323,
 0.8831969335957732,
 -0.080490689550843,
 -0.1952522539230525,
 -0.073589758839097,
 0.4203038108765256,
 -0.6849045730363741,
 48.5194011117088,
 -0.384928542124643,
 -0.2174921010384183,
 8.452783629250677,
 -0.2486851990984222,
 -0.7319569915254238,
 -0.0466445825557655,
 -0.2305517555859552,
 -0.2457476267953926,
 0.2938804198291711,
 -0.9933224027425844,
 -0.7735615079365079,
 8.698430083972251,
 0.0176931185062492,
 -0.0226011688984242,
 0.2215115618968322,
 -0.1093691907299539,
 -0.1520907256661797,
 0.0820956757200295,
 0.753175355450237,
 -0.1810121107266435,
 0.1106944811196197,
 0.0302410727022013,
 -0.2384732542576267,
 -0.5287272727272727,
 0.3333333333333332,
 -0.8765432098765432,
 8.262890624999999,
 0.5341795639522626,
 -0.2125068719076416,
 0.3557192223114243,
 -0.1739443872296602,
 -0.0500249345468146,
 0.1436070737228914,
 0.6328322240073445,
 -0.1965948624240081,
 0.3974849644614544,
 -0.1215649452269171,
 -0.4172486282334496,
 0.1566139830638011,
 -0.9746788602844004,
 6.724425887265135,
 0.394054054054054,
 0.0104691740984879,
 0.4014773599386032,
 0.0503114518447531,
 0.0088633993743483,
 -0.0558139534883721,
 0.5290777230432404,
 0.1655555058391873,
 -0.1278743905716149,
 0.1030460427854562,
 -0.2144937946446385,
 -0.2501016053647632,
 0.0547388388320573,
 -0.136039565803841,
 0.0935989889227566,
 -0.0984364377974166,
 -0.085281254712713,
 0.5912950292638695,
 0.2259635308744301,
 0.2319361108763626,
 0.1509518092951465,
 -0.2930921444749077,
 0.7584418869356269,
 -0.5028768699654775,
 0.5,
 -0.2024819958847736,
 0.3192775941304522,
 0.184318279044185,
 0.0219309561896898,
 0.1569379923247829,
 0.122512220670391,
 0.012169991057195,
 0.2424900122925632,
 0.6460449226298131,
 -0.0670823902855908,
 -0.0436690893716402,
 -0.0905473684210526,
 0.1301881988008981,
 -0.8938205354033959,
 -0.8983410493827161,
 9.001897533206833,
 0.1383039271485486,
 0.1344166666666666,
 -0.0206420333504738,
 0.1034353435343535,
 0.0196451634831078,
 0.5252000000000001,
 0.210595331759769,
 0.0044049682264588,
 -0.0294054209504637,
 0.1723333333333332,
 -0.3287208163523204,
 -0.8630459337349398,
 3.123711340206185,
 0.2348333333333334,
 -0.0929275205830747,
 0.3822632244624657,
 -0.0203993756391626,
 -0.0847252747252746,
 0.4827710409412893,
 0.3404048582995951,
 -0.1238975474205629,
 -0.0860166862028545,
 -0.0241032024442683,
 0.025007730364873,
 0.889664014480184,
 -0.6715756704980842,
 -0.9268440879815288,
 7.970930232558139,
 0.5150449032496991,
 -0.0365436323637251,
 -0.0841050361537485,
 0.1218836565096952,
 0.2222222222222223,
 -0.1564141414141414,
 0.544632700712447,
 -0.1141085271317829,
 0.316940847042352,
 -0.16,
 -0.0116279069767442,
 -0.9424569827931172,
 4.816411682892906,
 0.0758010521281684,
 0.2703934207601688,
 0.1293850056862915,
 0.0115414407436096,
 0.0241212956581668,
 0.0677433826828173,
 0.4005602240896357,
 0.0239,
 0.072565680242211,
 -0.1418229830631941,
 0.0530001591596369,
 -0.679161628375655,
 0.0979899497487437,
 0.2053775743707093,
 0.0702420503084955,
 0.018181818181818,
 0.1291376306620206,
 -0.0755062680810028,
 0.2481485344737664,
 0.4064850409493565,
 -0.0157456922162805,
 0.0630848173860547,
 -0.0626916524701873,
 -0.3093420574336605,
 -0.3547368421052631,
 0.6585100598151168,
 2.0918852459016395,
 -0.1966808939317622,
 0.1908784898686557,
 -0.4079421382253506,
 0.2497074654809268,
 0.0430337078651685,
 0.895938812883766,
 -0.2426136363636364,
 0.2582895723930982,
 -0.1150857528965202,
 -0.3068181818181819,
 -0.1042571113846949,
 -0.7163628472222222,
 0.953710788064269,
 0.2275961099144965,
 0.2760527435133986,
 0.0458333333333333,
 -0.3227091633466136,
 0.4498823529411766,
 -0.1798117494320026,
 0.4344083893945392,
 0.5517621904958963,
 -0.3177474554424642,
 0.6971986970684039,
 -0.4626132350683248,
 -0.0125714285714284,
 -0.6620370370370371,
 0.9861943493150682,
 0.4015841370763513,
 -0.1000691988313086,
 0.2859583920714255,
 -0.1481247716174467,
 0.2711355482763999,
 -0.2660674295180538,
 0.897007189433205,
 -0.3059227921734532,
 0.2682539682539682,
 -0.066758448060075,
 -0.1953437223399405,
 -0.4347333333333333,
 -0.6072650076659984,
 1.2198198198198202,
 0.988568722943723,
 0.1037790401034048,
 -0.1559322033898306,
 0.0143483023001098,
 -0.1111830975776555,
 -0.0240949218433627,
 0.8876301921241543,
 -0.1042866564080017,
 -0.0968684042605408,
 -0.180249463300633,
 0.1904461977060265,
 0.1862103533736181,
 -0.7980186863233015,
 4.083217108321711,
 0.4175964880190232,
 0.1496774193548387,
 -0.0301487093153759,
 0.0412694738973833,
 0.0585685707935095,
 -0.132283464566929,
 0.402979431336963,
 0.1017948579744514,
 -0.2013149655604257,
 0.151313210505684,
 -0.2280175348995574,
 -0.8507594343523445,
 0.385112670853343,
 0.600080010668089,
 0.1975997999833318,
 0.0855949895615866,
 -0.1185897435897436,
 0.0363636363636363,
 0.0900350877192983,
 0.5772870662460567,
 0.1428571428571428,
 -0.3589285714285714,
 0.1058495821727019,
 -0.1939546599496221,
 -0.244,
 0.8571428571428572,
 -0.5276442307692307,
 0.2487041749128262,
 0.4301886792452829,
 0.1972031662269129,
 0.1104817737030017,
 0.0717050032746542,
 -0.2627777777777778,
 0.6932429037930166,
 0.1289461191549965,
 0.3139027595269381,
 -0.2019042285074208,
 -0.0100501253132831,
 -0.1101293703638066,
 -0.8033514466983414,
 -0.1595052083333333,
 -0.7581547465358465,
 3.4170818505338074,
 0.3800354495649372,
 -0.2177009749547551,
 0.2429850746268655,
 0.1375480307396734,
 0.0943157228057212,
 0.0032796373106973,
 0.4553889049129891,
 0.011494632535095,
 0.0982268229761942,
 -0.1481668698522196,
 -0.0809829656520526,
 0.2142206016408387,
 -0.3513513513513513,
 1.833333333333333,
 -0.9699414488017428,
 5.793884484711212,
 0.685030838473079,
 -0.1592224365632883,
 0.5840098835157079,
 -0.2496935933147631,
 0.0852885852885851,
 0.3835347776510831,
 0.4089800224170898,
 0.1420917173607863,
 -0.1293303013541474,
 -0.0223529411764705,
 -0.3503249097472924,
 0.1522560569015336,
 -0.4444444444444444,
 -0.8596064814814814,
 3.3458367683429517,
 0.3778810585222423,
 -0.0189991051146143,
 -0.0519963511332537,
 0.1441894892672095,
 -0.1283477810842282,
 0.2281430903963186,
 0.5698573845781967,
 -0.0415736392331972,
 -0.070166278415937,
 0.0523951449181461,
 -0.0970284025611557,
 -0.3716363636363635,
 -0.3705150462962963,
 0.7903930131004366,
 0.336713735558408,
 -0.0269854988956113,
 0.2214765100671143,
 0.0804783451842274,
 -0.044570744839964,
 0.1919223544145272,
 0.488836354084581,
 -0.0216566690190542,
 -0.0257427528064559,
 0.0136742248958816,
 -0.0162288009860537,
 -0.4608816705336427,
 -0.3518677913582373,
 0.353386454183267,
 0.4973015405750172,
 0.110819844026476,
 0.2530383480825957,
 0.1446866613305713,
 0.0842382362619282,
 0.1290212443095599,
 0.5183797587446657,
 0.0071146419996239,
 -0.1758734344100198,
 0.0294352903535435,
 -0.0496114996114996,
 -0.7826104729591629,
 -0.2132380594208348,
 1.648263224984066,
 0.5153575403868718,
 0.0477646311442863,
 0.0210504376823679,
 -0.3327766334502404,
 0.0588775169651796,
 0.0430488797835735,
 0.634241539081386,
 -0.1745019183654601,
 0.0271400306118638,
 0.0371628988878389,
 -0.2702679025108194,
 -0.4173549750288129,
 -0.8607104590785462,
 4.999408284023669,
 0.1396587434658251,
 0.3906533967979229,
 -0.1276370651565125,
 0.1262305607076614,
 -0.0451623119556611,
 0.0458721682311187,
 0.6417607509831285,
 0.0280095812084684,
 -0.154158367469653,
 0.2060914382192209,
 -0.2693079884327053,
 0.0454247542223342,
 -0.7730034722222222,
 -0.3626513702995538,
 1.917333333333333,
 0.3877970749542963,
 -0.173308084966244,
 0.2536101981874314,
 -0.0825024826216485,
 -0.080309983548359,
 0.3921291719625288,
 0.2049166469414669,
 0.1129570903376082,
 -0.2415653840334863,
 0.156193895870736,
 -0.1838336783988956,
 -0.3230454849733997,
 -0.5878005620901425,
 2.4532828282828283,
 0.37308957952468,
 -0.0722692655908824,
 -0.0582089552238804,
 0.1124588565159088,
 0.1150073968549669,
 0.2136363636363636,
 0.4294969126429799,
 -0.0747202945758389,
 -0.0816726359935102,
 -0.0198006600220007,
 -0.0698180581533753,
 1.7224334600760458,
 0.1213472281908036,
 0.3473053892215569,
 0.2718666666666665,
 0.2754656323164552,
 -0.1917808219178082,
 -0.0705661016949152,
 0.420678889646696,
 0.1809173200248506,
 0.0283696885638633,
 0.2087060932505793,
 -0.0356258394895904,
 -0.0819831485330228,
 -0.9829316475701304,
 -0.8577546296296297,
 4.637917005695687,
 0.0548419685380288,
 0.118620878369134,
 0.1942270058708415,
 -0.036050798852929,
 -0.0287930301742457,
 0.1963680122524889,
 0.3427212874908558,
 0.0213838191228548,
 0.0890785438058407,
 -0.1776049957144607,
 0.0487605151492593,
 -0.5208688245315162,
 -0.0047407407407406,
 0.2616850253051503,
 0.0554506842850399,
 0.0739995528727923,
 -0.0126977518734388,
 0.0968796120598778,
 -0.056607400288323,
 0.5246536267318664,
 0.1595616731257516,
 -0.1459605854558028,
 0.0715876121719183,
 -0.0933131847374385,
 0.9200000000000002,
 -0.4546440972222222,
 0.392757660167131,
 0.2506666666666666,
 0.0314118184587268,
 0.2550481745357895,
 0.0802694276133888,
 0.0613172870095568,
 0.3722773801277612,
 0.3335576743316508,
 -0.0428979980934223,
 0.0229816029997658,
 -0.0277916982861071,
 -0.0995287187039765,
 -0.8372313630564914,
 -0.07516077170418,
 0.1508039982616253,
 0.093655589123867,
 0.1826657458563536,
 0.1211678832116787,
 -0.1075520833333332,
 0.122993872191421,
 0.5169546576588282,
 0.0044107571085989,
 0.0445534001279044,
 -0.2288163265306122,
 0.0585371017254154,
 -0.5750500000000001,
 0.1161313095658314,
 0.1806873286949188,
 0.1848214285714284,
 -0.1653353428786735,
 0.408450704225352,
 -0.2610897435897436,
 0.3381625748243253,
 0.6215235008103728,
 0.0794818487126178,
 0.0666666666666666,
 -0.2697222222222222,
 0.1354602510460252,
 1.7496335999330008,
 -0.3157894736842105,
 -0.8239182692307692,
 0.2890911389204904,
 0.0242204353794861,
 0.092005744375299,
 0.3657724004909697,
 -0.0220824239311849,
 0.0265196271497965,
 0.2679370763524746,
 0.301795440790801,
 0.0539284053928403,
 -0.1782826054991911,
 0.1008320658495123,

In [43]:
pokemon_year_card = pokemon_year_card.replace([np.inf, -np.inf], np.nan).dropna()

In [44]:
pokemon_year_card.columns = pokemon_year_card.columns.str.lower()

In [45]:
pokemon_year_card

,card name,unnamed: 1,card name.1,year,graded,yoy_growth,expected_price,rarity,set_name
59,Blastoise Base Set,2,Blastoise Base Set,2022,461650.0,-0.174522,570437.040000,Rare Holo,Base Set
60,Blastoise Base Set,2,Blastoise Base Set,2022,461650.0,-0.174522,570437.040000,Rare Holo,Base Set
61,Blastoise Base Set,2,Blastoise Base Set,2022,461650.0,-0.174522,570437.040000,Rare Holo,Base Set
62,Blastoise Base Set,2,Blastoise Base Set,2022,461650.0,-0.174522,570437.040000,Rare Holo,Base Set
63,Blastoise Base Set,2,Blastoise Base Set,2022,461650.0,-0.174522,570437.040000,Rare Holo,Base Set
...,...,...,...,...,...,...,...,...,...
5974,Venusaur Base Set,121,Venusaur Base Set,2025,314455.5,0.216241,423651.499454,Rare Holo,Base Set
5975,Venusaur Base Set,121,Venusaur Base Set,2025,314455.5,0.216241,423651.499454,Rare Holo,Base Set
5976,Venusaur Base Set,121,Venusaur Base Set,2025,314455.5,0.216241,423651.499454,Rare Holo,Base Set
5977,Venusaur Base Set,121,Venusaur Base Set,2025,314455.5,0.216241,423651.499454,Rare Holo,Base Set
5978,Venusaur Base Set,121,Venusaur Base Set,2025,314455.5,0.216241,423651.499454,Rare Holo,Base Set

In [46]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import streamlit as st

# Ensure categorical variables are properly formatted as category dtype
pokemon_year_card['graded'] = pokemon_year_card['graded'].astype('category')
pokemon_year_card['rarity'] = pokemon_year_card['rarity'].astype('category')
pokemon_year_card['set_name'] = pokemon_year_card['set_name'].astype('category')

# Define the model using lowercase variables
model = ols(
    'yoy_growth ~ graded + C(rarity) + C(set_name) + graded:C(rarity) + graded:C(set_name)',
    data=pokemon_year_card
).fit()


# Run ANOVA
anova_table_growth_poke = sm.stats.anova_lm(model, typ=2)

# Display ANOVA table in Streamlit
st.dataframe(anova_table_growth_poke)

c:\Users\amyby\miniconda3\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 110, but rank is 5
  warnings.warn('covariance of constraints does not have full '
c:\Users\amyby\miniconda3\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 11, but rank is 0
  warnings.warn('covariance of constraints does not have full '
c:\Users\amyby\miniconda3\Lib\site-packages\statsmodels\base\model.py:1923: RuntimeWarning: invalid value encountered in divide
  F /= J
c:\Users\amyby\miniconda3\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 14, but rank is 0
  warnings.warn('covariance of constraints does not have full '
c:\Users\amyby\miniconda3\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 1210, but rank is 33
  warnings.warn('covariance of constraints does not have full '
c:\Users\amyby\miniconda3\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 1540, but rank is 33
  warnings.warn('covariance of constraints does not have full '
2025-10-13 10:19:00.173 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-13 10:19:00.175 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-13 10:19:00.176 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [47]:
anova_table_growth_poke

                          sum_sq      df             F  PR(>F)
graded             -6.103764e-18   110.0 -3.734956e-17     1.0
C(rarity)                    NaN    11.0           NaN     NaN
C(set_name)                  NaN    14.0           NaN     NaN
graded:C(rarity)    5.657802e-11  1210.0  3.147334e-11     1.0
graded:C(set_name)  9.032034e-12  1540.0  3.947710e-12     1.0
Residual            8.463808e+00  5697.0           NaN     NaN

In [ ]:
pokemon_final_26.columns = pokemon_final_26.columns.str.lower()

In [ ]:
pokemon_final26_volatility = pokemon_final_26.groupby('card name')['graded'].std()
pokemon_final_26 = pd.merge(
    pokemon_final_26,
    pokemon_final26_volatility,
    on='card name',
    how='left'
)
pokemon_final_26.rename(columns={'graded_y': 'volatility'}, inplace=True)
pokemon_final_26.rename(columns={'graded_x': 'graded'}, inplace=True)
pokemon_final_26.rename(columns={'set name': 'set_name'}, inplace=True)

In [67]:
# Define the model using lowercase variables
model = ols(
    'volatility ~ graded + C(rarity) + C(set_name) + graded:C(rarity) + graded:C(set_name)',
    data=pokemon_final_26
).fit()


# Run ANOVA
anova_table_volatility_poke = sm.stats.anova_lm(model, typ=2)

c:\Users\amyby\miniconda3\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 11, but rank is 2
  warnings.warn('covariance of constraints does not have full '
c:\Users\amyby\miniconda3\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 14, but rank is 2
  warnings.warn('covariance of constraints does not have full '

In [69]:
anova_table_volatility_poke

                          sum_sq      df             F        PR(>F)
C(rarity)           9.053373e+11    11.0  4.576002e+02  0.000000e+00
C(set_name)         1.045664e+11    14.0  4.152718e+01  2.538376e-93
graded              8.523210e-02     1.0  4.738836e-10  9.999826e-01
graded:C(rarity)    2.063846e+09    11.0  1.043165e+00  3.526465e-01
graded:C(set_name)  2.626713e+09    14.0  1.043165e+00  3.526465e-01
Residual            2.232047e+11  1241.0           NaN           NaN